### PR TITLE
Change tn_keras layers import method

### PR DESCRIPTION
**Pull request by jacksonwb**
* Add tn_keras layers to __init__.py file
* Change documentation to reflect
* Change layer test file naming

### CODE REVIEW

**Comment by jacksonwb** [comment]
Expecting this to fail... Will debug the travis keras_serialization error

**Comment by jacksonwb** [comment]
@bpenchas

**Comment by jacksonwb** [comment]
Added an intermediate import module called 'layers'. 
This avoids the problem of pytest double importing `__init__.py` files.
Layer imports will now look like:
`from tensornetwork.tn_keras.layers import DenseMPO`

**Comment by jacksonwb** [comment]
@bpenchas

**Comment by bpenchas** [comment]
LGTM

**Review by bpenchas — APPROVED** [review]
LGTM

**Pull request merged**
