### PR TITLE
Add initialization functions to Tensor.

### PR DESCRIPTION
**Pull request by alewis**
- tn.ones, tn.zeros, tn.eye, tn.randn, tn.random_uniform refer to tn.Tensor.
- Move the equivalent Node functions to linalg/node_linalg.py
- __init__.py and the few pieces of code which used the old linalg/linalg.py are adjusted accordingly.

### CODE REVIEW

**Comment by mganahl** [comment]
Hey @alewis, fix the build and we can pull it in

**Comment by alewis** [comment]
The errors in MERA should be fixed. I'm not totally sure what's going on with eigh_lanczos - is this error familiar to you?

**Comment by mganahl** [comment]
I'll check

**Comment by mganahl** [comment]
Hey @alewis, there is still a syntax error:
ImportError while loading conftest '/home/travis/build/google/TensorNetwork/conftest.py'.
conftest.py:17: in <module>
    import tensornetwork
tensornetwork/__init__.py:30: in <module>
    from tensornetwork.linalg.initialization import (
tensornetwork/linalg/initialization.py:23: in <module>
    from tensornetwork.tensor import Tensor
E     File "/home/travis/build/google/TensorNetwork/tensornetwork/tensor.py", line 15
E       from __future__ import annotations
E                                        ^
E   SyntaxError: future feature annotations is not defined

**Comment by mganahl** [comment]
you can see the errors by clicking on Details in the travis build

**Comment by mganahl** [comment]
Hey @alewis, I merged the master branch into `experimental_ncon` to fix the eigsh_lanczos error. Unfortunately this resulted in a bunch of conflicts in this PR

**Comment by mganahl** [comment]
conflicts should be easy to fix

**Pull request merged**
