### PR TITLE
Change optimal to dynamic_programming

### LINKED ISSUE #743: add dynamic programming contractor of opt_einsum
We should update this asap

### PR DESCRIPTION
**Pull request by Thenerdstation**
Fixes #743

### CODE REVIEW

**Comment by Thenerdstation** [comment]
@gevenbly @alewis @mganahl We're all cool with this change right?

**Comment by alewis** [comment]
Fine by me yeah

**Comment by gevenbly** [comment]
Sure, looks good to me.

**Comment by mganahl** [comment]
SGTM

**Pull request merged**
