### PR TITLE
Fix build

### LINKED ISSUE #791: latest pylint break build

### PR DESCRIPTION
**Pull request by mganahl**
latest pytype and pylint break the build. 
fixes #791

### CODE REVIEW

**Comment by alewis** [comment]
Thank gosh

**Comment by mganahl** [comment]
This PR changes some parts of the code to conform to the rquirements by the latest versions of pylint and pytype.

**Comment by mganahl** [comment]
@alewis can you take a look?

**Comment by alewis** [comment]
This all looks good to me. Let us never speak of this again

**Pull request merged**
