### PR TITLE
bugfix in lanczos in numpy backend

### PR DESCRIPTION
**Pull request by mganahl**

### CODE REVIEW

**Comment by Thenerdstation** [comment]
There are so many unneeded formating changed that it's hard to tell what you've actually fixed. Can we please stop submitting these unneeded changes? It's beginning to smash our code history for no useful reason.

**Comment by mganahl** [comment]
sorry about that. I'm using yapf on emacs with the tensornetwork stylefile, and that's what my auto-formatter (pyyapf) is giving me. If you can let me know which editor and autoformatter you are using I can try to figure out how to adapt my settings so they match.

**Comment by mganahl** [comment]
can you confirm that the current formatting of numpy_backend.py in master is the desired one?
thanks!

**Comment by Thenerdstation** [comment]
It's fine for this time but for the future let's figure out a new workflow.

**Comment by mganahl** [comment]
we can add an acion on github that checks formatting

**Comment by mganahl** [comment]
like so 
https://github.com/marketplace/actions/yapf-python-code-formatting-check

**Comment by Thenerdstation** [comment]
We already have a format checker (pylint)

**Comment by mganahl** [comment]
can we configure it to detect style differences like the one above (new lines vs continued line)?

**Pull request merged**
