### PR TITLE
Classification with MPS experiment

### PR DESCRIPTION
**Pull request by stavros11**
Simple Matrix Product State classifier ([arXiv:1605.05775](https://arxiv.org/abs/1605.05775)) trained using automatic gradients. Note that I had to add some methods to `TensorNetwork` for this implementation.

### CODE REVIEW

**Comment by Thenerdstation** [comment]
Please add a unit test.

**Comment by sleichen** [comment]
@stavros11 Update on unit test status?

**Comment by stavros11** [comment]
I will try to add tests at least for `batchtensornetwork.py` today, but might need more time for the rest (actually not sure how to unit test training). Sorry for the delay, I won't have much time in the next few days but I expect to do more after Wednesday.

**Comment by stavros11** [comment]
@Thenerdstation I added some tests, you can take a look at this when you have time.

**Pull request merged**
