### PR TITLE
fix bug in print_msg in dmrg

### PR DESCRIPTION
**Pull request by mganahl**
and fix some other things once I'm at it
depends on #697

### CODE REVIEW

**Comment by pedersor** [comment]
Apologies, as I am still trying to understand the code, but on the second sweep (moving to the right) the print still seems to miss the 2nd to last rightmost site. This seems to be due to initial_site = 1 being fixed for sweeps > 1.

**Comment by mganahl** [comment]
> Apologies, as I am still trying to understand the code, but on the second sweep (moving to the right) the print still seems to miss the 2nd to last rightmost site. This seems to be due to initial_site = 1 being fixed for sweeps > 1.

Hi Ryan, yes you're right! Thanks for pointing it out again. I've fixed it

**Comment by mganahl** [comment]
@Thenerdstation should be good to do

**Comment by mganahl** [comment]
pls pull in #697 first!

**Comment by pedersor** [comment]
Looks good. I will start looking into the two-site implementation.

**Comment by Thenerdstation** [comment]
Fix the import and this can be merged.

**Pull request merged**
