### PR TITLE
Add documentation stubs

### LINKED ISSUE #550: Some doc links to github yield error
The "Edit on GitHub" links in the top right of some doc pages yield 404 errors when followed, for example [tn.Node](https://tensornetwork.readthedocs.io/en/latest/stubs/tensornetwork.Node.html) and [tn.contractors.optimal](https://tensornetwork.readthedocs.io/en/latest/stubs/tensornetwork.contractors.optimal.html#tensornetwork.contractors.optimal).

The links at the top of list pages work, for example [common functions](https://tensornetwork.readthedocs.io/en/latest/network.html) and [contractors](https://tensornetwork.readthedocs.io/en/latest/contractors.html).

Possibly those are meant to be links to edit the doc pages themselves, rather than the source code?

### PR DESCRIPTION
**Pull request by Lazersmoke**
These are linked to by the "Edit on GitHub" links in the documentation. Adding these means contributors can immediately edit them on GitHub without download, building docs, etc.

Closes #550

### CODE REVIEW

**Comment by Thenerdstation** [comment]
My concern with adding the stubs in (I tried doing it before) is every time the website is rebuilt, the stubs get overwritten, so I'm not sure there having these here is a good idea.

**Comment by Thenerdstation** [comment]
Oh... well that works.

**Comment by Lazersmoke** [comment]
* small asterisk on this, existing stubs will no longer be overwritten due to code changes (ie, you add another static method to BaseCharge, the stub will need to be deleted or updated)

**Comment by Lazersmoke** [comment]
my git-fu was weak, now it is rebased and not a messy merge commit

**Comment by Thenerdstation** [comment]
We squash and merge anyway so it doesn't really matter.

**Pull request merged**
