### PR TITLE
use einsum when calculating inner products with tensordot

### PR DESCRIPTION
**Pull request by mganahl**

### CODE REVIEW

**Comment by mganahl** [comment]
Hey @Thenerdstation, can you let me know what you think of this? It turns out that 
einsum is a lot faster for calculating inner product like contractions (with possible permutations)
than np.tensordot or np.dot. This is a hotfix that would improve e.g. speed of ncon with numpy backend in certain cases.

**Comment by Thenerdstation** [comment]
Add a test

**Comment by Thenerdstation** [comment]
That that is why you add a test. :)

**Comment by mganahl** [comment]
that bit of code broke quite a few tests :)

**Pull request merged**
