### PR TITLE
added eigh to backends

### PR DESCRIPTION
**Pull request by mganahl**

### CODE REVIEW

**Comment by mganahl** [comment]
Hey  @Thenerdstation please pull this in before the infinite MPS PR. thanks!

**Comment by mganahl** [comment]
Actually no, pls pull it after #376! The order should be 
#375 -> #376 -> #380 -> #382

**Comment by Thenerdstation** [comment]
Tag me here when you're ready for review!

**Comment by mganahl** [comment]
Hey Chase, this should be ready! Thanks for reviewing!

**Pull request merged**
