### PR TITLE
Converting AUTHORS.md to AUTHORS

### PR DESCRIPTION
**Pull request by kshithijiyer**
All the contents of the markdown file are marked as title instead of propering structuring it in the form of title, body and list of contributors.

### CODE REVIEW

**Comment by Thenerdstation** [comment]
Hm, I think the actual mistake was marking AUTHORS as a markdown file. Other related projects have it just as a normal text file. See [cirq](https://github.com/quantumlib/Cirq/blob/master/AUTHORS), [copybara](https://github.com/google/copybara/blob/master/AUTHORS), and [tensorflow](https://github.com/tensorflow/tensorflow/blob/master/AUTHORS). 

Can you revert your changes and instead change AUTHORS.md -> AUTHORS?

**Comment by kshithijiyer** [comment]
> Hm, I think the actual mistake was marking AUTHORS as a markdown file. Other related projects have it just as a normal text file. See [cirq](https://github.com/quantumlib/Cirq/blob/master/AUTHORS), [copybara](https://github.com/google/copybara/blob/master/AUTHORS), and [tensorflow](https://github.com/tensorflow/tensorflow/blob/master/AUTHORS).
> 
> Can you revert your changes and instead change AUTHORS.md -> AUTHORS?
Done.

**Comment by Thenerdstation** [comment]
Strange, I don't know why the google bot isn't responding.

**Comment by kshithijiyer** [comment]
It did add cla:yes at the start but the second time I guess something went wrong.

**Pull request merged**
