### PR TITLE
MPS classifier

### PR DESCRIPTION
**Pull request by mganahl**
An implementation of DMRG style optimization of a linear MPS classifier

### CODE REVIEW

**Comment by Thenerdstation** [comment]
looks like one of your tests is failing because it doesn't have the training data. Can you mock the data in the test instead?

**Comment by mganahl** [comment]
Oh I missed that one! I'll remove it now

**Comment by mganahl** [comment]
oh damn, yes forgot the data ...

**Comment by mganahl** [comment]
should be fixed

**Pull request merged**
