### PR TITLE
temporarily switch to tf.tensordot instead of tensordot2

### LINKED ISSUE #940: Buggy interplay between ``tf.vectorized_map`` and ``tn.contractors.*``
When a function ``f`` has, say ``tn.contractors.optimal()`` inside, the results of the function is of course right, but the results for ``tf.vectorized_map(f, batched_input)`` might be wrong. 
See a full demo script at  https://gist.github.com/refraction-ray/3a24e1ca09d9c2850d62b40cbf57946c. 
The results are always correct for individual input (jitted or not) and for ``jax.vmap`` interface but become wrong for ``tf.vectorized_map`` interface. I suspect the problem may be related to the interplay of ``tf.vectorized_map`` and the path solver provided by opteinsum, though I cannot see why they are entangled.

The output for the above demo script in tensorflow case is
```bash
$ python vectorized_map_bug.py tensorflow

3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0]
tensornetwork version: 0.4.5
tensorflow version: 2.5.0
tf.Tensor((-0.4161468+0.90929735j), shape=(), dtype=complex64)
tf.Tensor((-0.65364355-0.7568025j), shape=(), dtype=complex64)
jitted
tf.Tensor((-0.4161468+0.90929735j), shape=(), dtype=complex64)
tf.Tensor((-0.65364355-0.7568025j), shape=(), dtype=complex64)
mapfn
tf.Tensor([-0.4161468 +0.90929735j -0.65364355-0.7568025j ], shape=(2,), dtype=complex64)
vectorized map
tf.Tensor([0.99999994+0.j 0.99999994+0.j], shape=(2,), dtype=complex64)
```

### PR DESCRIPTION
**Pull request by mganahl**
`tf.matmul` with `transpose_a` and ` transpose_b` arguments has a bug for complex dtypes if wrapped into `tf.vectorized_map` (see https://github.com/tensorflow/tensorflow/issues/52148). Our modified version of `tf.tensordot`, `tensordot2`, uses a `tf.matmul` with these arguments to improve efficiency. This unfortunately causes the afore mentioned bug to hit us in certain use cases.
Hence we temporarily revert to using `tf.tensordot` in the `TensorflowBackend` directly.
fixes #940

### CODE REVIEW

**Comment by refraction-ray** [comment]
BTW, there is another call for ``tensordot2`` on L111 of the same file, and it also induce similar issues with ``tf.vectorized_map``

**Comment by mganahl** [comment]
thanks, yes your're right! Fixed it

**Comment by jacksonwb** [comment]
Should we deprecate the tensorflow2 module?

**Comment by mganahl** [comment]
the `tensordot2` module applies some tricks which make it more efficient than `tf.tensordot`. From looking at the latest implementation of `tf.tensordot`, it seems that these improvements are still valid. I would say we leave it in for now.

**Review by jacksonwb — APPROVED** [review]

**Comment by jacksonwb** [comment]
Sounds good. Should we at least open an issue to track the tf bug and re-use tensordot2 when it is resolved?

**Comment by mganahl** [comment]
good point, yes we should!

**Pull request merged**
