### PR TITLE
Import scipy.sparse.linalg in numpy_backend.py

### PR DESCRIPTION
**Pull request by alewis**
I don't know how this ever worked.

### CODE REVIEW

**Comment by Thenerdstation** [comment]
Yeah that's bad.

Can you add a test that clearly breaks without this and works with this? We apparently missed it earlier.

**Comment by mganahl** [comment]
lol, I was just fixing this as well

**Comment by mganahl** [comment]
there's actually a few more things that need to be fixed there, I'll submit a PR

**Comment by Thenerdstation** [comment]
Yeah dang we're clearly missing a LOT of tests. Unless just doing `import sp` works?

**Comment by mganahl** [comment]
It's kind of strange: test are working fine, but it breaks if you run it in a jupyter notebook

**Comment by mganahl** [comment]
I guess we are importing scipy.sparse.linalg and scipy.linalg somewhere else at some point

**Comment by Thenerdstation** [comment]
Do the actually cover these methods? :upside_down_face:

**Comment by mganahl** [comment]
yeah they do, just checked

**Comment by mganahl** [comment]
looks like jupyter's import system works a bit different than the one of the python interpreter

**Comment by mganahl** [comment]
this fixes it

**Pull request merged**
