### PR TITLE
Experimental ncon

### PR DESCRIPTION
**Pull request by alewis**
Adds operators and more functions to Tensor, linalg.operations, and linalg.linalg

### CODE REVIEW

**Comment by alewis** [comment]
I'll be breaking this one up too, so don't sweat it right now - I just needed the functions together to write vuMPS.

**Comment by mganahl** [comment]
no problem. Should I merge it or do you still want to change stuff?

**Comment by alewis** [comment]
It would be great if you merged it (I thought it would be too big), but let me get it building

**Comment by mganahl** [comment]
yes it's a lot. We'll have to break it up once we decide to merge it into master. I'll look through it as good as I can

**Comment by alewis** [comment]
It's not quite as big as it looks, since most of the changes are actually those to the backends in the backend_functions commit. But yes, it's not small.

**Pull request closed without merging**
