### PR TITLE
fix tensorflow import error

### PR DESCRIPTION
**Pull request by mganahl**
moved tensorflow import in TensorFlowBackend to __init__
importing it as class variable prompts import error

### CODE REVIEW

**Comment by Thenerdstation** [comment]
This is broken internally. 

The problem is is that if any code isn't imported simply by `import tensornetwork` with the exception of importing the backend libraries (`numpy`, `tensorflow`, etc) then that code doesn't get picked up by the bazel par_binary. https://google.github.io/subpar/subpar.html 

I'm still thinking about how to work around this...

**Comment by MichaelMarien** [comment]
Can you clarify? Trying to look into root cause of this but I'm a bit confused atm.

**Comment by Thenerdstation** [comment]
Basically our internal build system really does not like dynamic imports.

@MichaelMarien @mganahl @gecrooks I'll take the lead on this one guys. It's super fragile at the moment and I need to make sure everything works both on the pip and internally.

**Comment by gecrooks** [comment]
That's fixable. Just less elegant.

**Comment by Thenerdstation** [comment]
Closing this PR as it breaks our stuff internally.

**Pull request closed without merging**
