### PR TITLE
Return empty dict for empty sequence input to MPS left_envs and right_envs

### PR DESCRIPTION
**Pull request by AidanGG**
The `min` and `max` calls prevent input of empty sequences by raising `ValueError`, so this PR just enables these cases.

### CODE REVIEW

**Comment by AidanGG** [comment]
`left_envs` and `right_envs` do not have unit tests, so would you like me to write tests for their numerical correctness as well?

**Comment by Thenerdstation** [comment]
Sure! You can do that in a later PR if you like. I'll never say no to more testing.

**Comment by Thenerdstation** [comment]
I'll pull this in once the test is added (you can do the numerics one later).

**Comment by AidanGG** [comment]
Okay, should be done now. I'll take a look at a numerics test later.

**Comment by MichaelMarien** [comment]
Looks good to me, pytype just complains that you cannot call `left_envs`with boolean type. If you just change the argument in your test `assert mps.left_envs(False) == {}`from `False`to `[]`, it should work.

@Thenerdstation, what about turning of the linter and type checker for the test files?

**Comment by Thenerdstation** [comment]
I still like the linter on test files as it helps me catch dumb errors sometimes. If you have a bunch of typing tests and you want to ignore all of them then use `#pytest: skip-file` at the top of the file.

**Comment by AidanGG** [comment]
I added the cases for `[]`, `()` and `range(0)` to be thorough.

**Pull request merged**
