### PR TITLE
Blocksparse new encoding

### PR DESCRIPTION
**Pull request by mganahl**
final part of block-sparse improvement.
Depends on #790

### CODE REVIEW

**Comment by mganahl** [comment]
The negative delta in `network_components.py` is due to silencing pytype in `AbstractNode._load_node`. I don't think it makes sense to add a test there.

**Comment by mganahl** [comment]
@Thenerdstation @gevenbly could you have a look? Would be helpful if this was merged.

**Comment by mganahl** [comment]
@Thenerdstation @gevenbly ping for review

**Comment by Thenerdstation** [comment]
I'm enjoying watching our coverage constantly go up!

**Review by gevenbly — APPROVED** [review]

**Pull request merged**
